app/main/log/__init__.py
from flask import Blueprint

log = Blueprint('log', __name__, url_prefix='/logs_info', template_folder='templates')
from . import views

app/main/log/views.py
# -*- coding:utf-8 -*-
from app import db
from app.models import Item, Log, Permission, User
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import login_required, current_user
from . import log
from ..decorators import permission_required


@log.route('/borrow/')
@login_required
@permission_required(Permission.BORROW_ITEM)
def item_borrow():
    item_id = request.args.get('item_id')
    the_item = Item.query.get_or_404(item_id)
    if the_item.hidden and not current_user.is_administrator():
        abort(404)

    result, message = current_user.borrow_item(the_item)
    flash(message, 'success' if result else 'danger')
    db.session.commit()
    return redirect(request.args.get('next') or url_for('item.detail', item_id=item_id))


@log.route('/return/')
@login_required
@permission_required(Permission.RETURN_ITEM)
def item_return():
    log_id = request.args.get('log_id')
    item_id = request.args.get('item_id')
    the_log = None
    if log_id:
        the_log = Log.query.get(log_id)
        the_user = the_log.user_id
        the_item = the_log.item_id
    if the_item:
        print(log_id)
        the_log = Log.query.filter_by(user_id=the_user, item_id=the_item,returned=0).first()
    if the_log is None:
        flash(u'Nie znaleziono wypożyczenia!', 'warning')
    else:
        print(the_log.returned)
        result, message = current_user.return_item(the_log)
        flash(message, 'success' if result else 'danger')
        db.session.commit()
    return redirect(request.args.get('next') or url_for('item.detail', item_id=item_id))


@log.route('/')
@login_required
def index():
    show = request.args.get('show', 0, type=int)
    if show != 0:
        show = 1

    page = request.args.get('page', 1, type=int)
    pagination = Log.query.filter_by(returned=show).order_by(Log.borrow_timestamp.desc()).paginate(page, per_page=10)
    print(pagination)
    logs = pagination.items
    return render_template("logs_info.html", logs=logs, pagination=pagination, title=u"Informacje o wypożyczeniach")

app/main/log/templates/logs_info.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        {% if request.args.get('show',0)!='1' %}
            <li role="presentation" class="active"><a href="#" role="tab">Aktualne wypożyczenia</a></li>
            <li role="presentation"><a href="{{ url_for('log.index',show=1) }}" role="tab">Historia wypożyczeń</a></li>
        {% else %}
            <li role="presentation"><a href="{{ url_for('log.index',show=0) }}" role="tab">Aktualne wypożyczenia</a></li>
            <li role="presentation" class="active"><a href="#" role="tab">Historia wypożyczeń</a></li>
        {% endif %}
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        {% if request.args.get('show',0)!='1' %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>Użytkownik</th>
                    <th>Email</th>
                    <th>Tytuł</th>
                    <th>Data wypożyczenia</th>
                    <th>Przewidywana data zwrotu</th>
                    {%- if current_user.is_authenticated -%}
                        <th>Operacje</th>
                    {%- endif -%}
                </tr>
                </thead>
                <tbody>
                {% for log in logs %}
                    <tr class="animated fadeIn delay-{{ loop.index0 }}">
                        <td><a href="{{ url_for('user.detail' ,user_id=log.user.id) }}">{{ log.user.name }}</a>
                            <a class="visible-xs-block"
                               href="{{ url_for('item.detail',item_id=log.item.id) }}">{{ log.item.title }}</a>
                            <p class="visible-xs-block">Data wypożyczenia: <span
                                    class="line-wrap">{{ log.borrow_timestamp }}</span>
                            </p>
                            <p class="visible-xs-block">Przewidywana data zwrotu: <span
                                    class="line-wrap">{{ log.return_timestamp }}</span>
                            </p>
                            {%- if current_user.is_administrator() -%}
                                    <a class="btn btn-primary visible-xs-block"
                                       href="{{ url_for('log.item_return',log_id=log.id,next=request.path) }}">
                                        Zwrot
                                    </a>
                            {%- endif -%}
                        </td>
                        <td class="hidden-xs">{{ log.user.email }}</td>
                        <td class="hidden-xs"><a
                                href="{{ url_for('item.detail',item_id=log.item.id) }}">{{ log.item.title }}</a></td>
                        <td class="hidden-xs">{{ log.borrow_timestamp }}</td>
                        <td class="hidden-xs">{{ log.return_timestamp }}</td>
                        {%- if current_user.is_authenticated -%}
                            <td class="hidden-xs">
                            {% if current_user.id == log.user.id or current_user.is_administrator() %}
                                <a class="btn btn-primary btn-block"
                                   href="{{ url_for('log.item_return',log_id=log.id,next=request.path) }}">
                                    Zwrot
                                </a>
                            {% else %}
                                <button class="btn btn-warning btn-block" disabled>Zwróć</button>
                            {% endif %}
                        {%- endif -%}
                        </td>
                    </tr>


                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>Użytkownik</th>
                    <th>Email</th>
                    <th>Wypozyczenia</th>
                    <th>Data wypożyczenia</th>
                    <th>Data zwrotu</th>
                </tr>
                </thead>
                <tbody>
                {% for log in logs %}
                    <tr class="animated fadeIn delay-{{ loop.index0 }}">
                        <td><a href="{{ url_for('user.detail' ,user_id=log.user.id) }}">{{ log.user.name }}</a>
                            <a class="visible-xs-block"
                               href="{{ url_for('item.detail',item_id=log.item.id) }}">{{ log.item.title }}</a>
                            <p class="visible-xs-block">Data wypożyczenia: <span
                                    class="line-wrap">{{ log.borrow_timestamp }}</span>
                            </p>
                            <p class="visible-xs-block">Data zwrotu: <span
                                    class="line-wrap">{{ log.return_timestamp }}</span>
                            </p>
                        </td>
                        <td class="hidden-xs">{{ log.user.email }}</td>
                        <td class="hidden-xs"><a
                                href="{{ url_for('item.detail',item_id=log.item.id) }}">{{ log.item.title }}</a></td>
                        <td class="hidden-xs">{{ log.borrow_timestamp }}</td>
                        <td class="hidden-xs">{{ log.return_timestamp }}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        {% endif %}
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}