app/main/user/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import Length, DataRequired, URL, Regexp, NumberRange
from flask_pagedown.fields import PageDownField
from flask_wtf.file import FileField, FileAllowed
from app import avatars


class EditProfileForm(FlaskForm):
    name = StringField(u'Nazwa użytkownika', validators=[DataRequired(message=u"Proszę wypełnić to pole!"), Length(1, 64, message=u"Długość od 1 do 64 znaków")])
    major = StringField(u'Zawód', validators=[Length(0, 128, message=u"Długość od 0 do 128 znaków")])
    headline = StringField(u'Motto', validators=[Length(0, 32, message=u"Maksymalnie 32 znaki")])
    about_me = PageDownField(u"O mnie")
    submit = SubmitField(u"Zapisz")


class AvatarEditForm(FlaskForm):
    avatar_url = StringField('', validators=[Length(1, 100, message=u"Długość ograniczona do 100 znaków"), URL(message=u"Podaj poprawny adres URL")])
    submit = SubmitField(u"Zapisz")


class AvatarUploadForm(FlaskForm):
    avatar = FileField('', validators=[FileAllowed(avatars, message=u"Prześlij zdjęcie")])

class TransactionProcessingForm(FlaskForm):
    street = StringField(u'Ulica', validators=[DataRequired(message=u"Proszę wypełnić to pole!"), Length(1, 64, message=u"Długość od 1 do 64 znaków")])
    house_nbr = IntegerField(u'Nr. Domu', validators=[DataRequired(message=u"Proszę wypełnić to pole!"),NumberRange(min=0, max=9999,message=u"Podaj poprawny numer domu/bloku")])
    flat_nbr = IntegerField(u'Nr. Lokalu', validators=[NumberRange(min=0, max=9999,message=u"Podaj poprawny numer mieszkania/lokalu")])
    postal_code = StringField(u'Kod pocztowy',validators=[DataRequired(message=u"Proszę wypełnić to pole!"),Regexp('[0-9]{2}\-[0-9]{3}',message="Podaj poprawny kod pocztowy")])
    city = StringField(u'Miasto', validators=[DataRequired(message=u"Proszę wypełnić to pole!"),Length(0, 64, message=u"Maksymalnie 32 znaki")])
    cardholder = StringField(u'Właściciel karty', validators=[DataRequired(message=u"Proszę wypełnić to pole!"),Length(0, 128, message=u"Maksymalnie 32 znaki")])
    card_nbr = StringField(u'Nr. karty', validators=[DataRequired(message=u"Proszę wypełnić to pole!"),Regexp('^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$',message="Podaj poprawny numer karty płatniczej")])
    submit = SubmitField(u"Zapisz")    

app/main/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__, url_prefix='/users', template_folder='templates')

from . import views

app/main/user/views.py
# -*- coding:utf-8 -*-
from flask import render_template, url_for, flash, redirect, request, abort, g
from flask_login import login_required, current_user
from app.models import User, Log, Permission, Cart, Item, Transaction, Payment
from .forms import EditProfileForm, AvatarEditForm, AvatarUploadForm, TransactionProcessingForm
from ..comment.forms import CommentForm
from app import db, avatars
from . import user
import json


@user.route('/')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.id.desc()).paginate(page, per_page=10)
    users = pagination.items
    return render_template("user.html", users=users, pagination=pagination, title=u"Zarejestrowani użytkownicy")

@user.route('/<int:user_id>/cart/', methods=['GET', 'POST'])
@login_required
def cart(user_id):
    class IntCart():
        def __init__(self,id,user_id,item_id,name,platform,price):
            self.id = id
            self.user_id = user_id
            self.item_id = item_id
            self.name = name
            self.platform = platform
            self.price = price

    cart = []
    items = []
    form = TransactionProcessingForm()
    cart_db = Cart.query.filter_by(user_id=user_id)
    total = 0
    submit_flag = 0
    for i,s in enumerate(cart_db):
        id = s.item_id
        the_item = Item.query.get_or_404(id)
        name = the_item.title
        platform = the_item.platform
        price = the_item.price
        cart.append(IntCart(i+1,user_id,id,name,platform,price))
        items.append(id)
        db.session.add(Log(current_user,the_item))
        total+=int(the_item.price)
        #pagination = cart.paginate(page, per_page=10)
    if form.validate_on_submit():
        submit_flag = 0
        payment = Payment(user_id,total,form.cardholder.data,form.card_nbr.data)
        db.session.add(payment)
        db.session.commit()
        transaction = Transaction(user_id,str(items).strip('[]'),total,payment.id)
        Cart.query.filter_by(user_id=user_id).delete()
        db.session.add(transaction)
        db.session.commit()
        flash(u'Informacje zaaktualizowane pomyślnie!', "info")
        return redirect(url_for('main.index')) 
    print(request.form.get('btn'))    
    if submit_flag==0:    
        flash(u'W formularzu wykryto błędy! Wróć do koszyka i uzupełnij formularz ponownie!', "info")  
        return render_template("user_cart.html",submit_flag=submit_flag,cart=cart, total=total,form=form,title=u"Koszyk") 

@user.route('/<int:user_id>/cart/delete/<int:item_id>', methods=['GET', 'POST'])
@login_required
def delete_from_cart(user_id,item_id):
    print(user_id)
    print(item_id)
    Cart.query.filter_by(user_id=user_id,item_id=item_id).delete()
    db.session.commit()
    flash(u'Usunięto pozycję z koszyka!', "info")  
    return redirect(url_for('user.cart',user_id=user_id))
        



@user.route('/<int:user_id>/')
def detail(user_id):
    the_user = User.query.get_or_404(user_id)

    show = request.args.get('show', 0, type=int)
    if show != 0:
        show = 1

    page = request.args.get('page', 1, type=int)
    pagination = the_user.logs.filter_by(returned=show) \
        .order_by(Log.borrow_timestamp.desc()).paginate(page, per_page=5)
    print(pagination.items)
    logs = pagination.items

    return render_template("user_detail.html", user=the_user, logs=logs, pagination=pagination,
                           title=u"Użytkownik: " + the_user.name)


@user.route('/<int:user_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(user_id):
    if current_user.id == user_id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION):
        the_user = User.query.get_or_404(user_id)
        form = EditProfileForm()
        if form.validate_on_submit():
            the_user.name = form.name.data
            the_user.major = form.major.data
            the_user.headline = form.headline.data
            the_user.about_me = form.about_me.data
            db.session.add(the_user)
            db.session.commit()
            flash(u'Informacje zaaktualizowane pomyślnie!', "info")
            return redirect(url_for('user.detail', user_id=user_id))
        form.name.data = the_user.name
        form.major.data = the_user.major
        form.headline.data = the_user.headline
        form.about_me.data = the_user.about_me

        return render_template('user_edit.html', form=form, user=the_user, title=u"Edytuj")
    else:
        abort(403)


@user.route('/<int:user_id>/avatar_edit/', methods=['GET', 'POST'])
@login_required
def avatar(user_id):
    if current_user.id == user_id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION):
        the_user = User.query.get_or_404(user_id)
        avatar_edit_form = AvatarEditForm()
        avatar_upload_form = AvatarUploadForm()
        if avatar_upload_form.validate_on_submit():
            if 'avatar' in request.files:
                forder = str(user_id)
                avatar_name = avatars.save(avatar_upload_form.avatar.data, folder=forder)
                the_user.avatar = json.dumps({"use_out_url": False, "url": avatar_name})
                db.session.add(the_user)
                db.session.commit()
                flash(u'Pomyślnie zaaktualizowano awatar!', 'success')
                return redirect(url_for('user.detail', user_id=user_id))
        if avatar_edit_form.validate_on_submit():
            the_user.avatar = json.dumps({"use_out_url": True, "url": avatar_edit_form.avatar_url.data})
            db.session.add(the_user)
            db.session.commit()
            return redirect(url_for('user.detail', user_id=user_id))
        return render_template('avatar_edit.html', user=the_user, avatar_edit_form=avatar_edit_form,
                               avatar_upload_form=avatar_upload_form, title=u"Zmień awatar")
    else:
        abort(403)

app/main/user/templates/avatar_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/fileinput.min.css') }}" rel="stylesheet">
    <style>
        main {
            display: flex;
        }

        #input_area {

        }
    </style>
{% endblock %}
{% block mycontent %}
    <div class="jumbotron">
        <div class="row">
            {% if user.avatar_url() %}
                <div class="col-md-4">
                    <div class="media-object avatar avatar-large"
                         style="background-image: url({{ user.avatar_url() }})"></div>
                </div>
            {% endif %}
            <div class="col-md-6" id="input_area">
                <p>Upewnij się, że podałeś poprawny adres URL</p>
                <p>Rozmiar przesłanego obrazu nie może być większy niż 1MB</p>
                <form method="post" class="form {% if avatar_edit_form.avatar_url.errors %} has-error{% endif -%}"
                      role="form" name="avatar_edit_form">
                    {{ avatar_edit_form.hidden_tag() }}
                    <div class="input-group  input-group">
                        {{ avatar_edit_form.avatar_url(placeholder="Link",class_="form-control") }}
                    <span class="input-group-btn">
                        {{ wtf.form_field(avatar_edit_form.submit,class_="btn btn-primary",button_map={'submit':'primary'}) }}
                    </span>
                    </div>
                    {% for error in avatar_edit_form.avatar_url.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </form>
                <form method="post" class="form" enctype="multipart/form-data" role="form" name="avatar_edit_form">
                    {{ avatar_upload_form.hidden_tag() }}
                    {{ wtf.form_field(avatar_upload_form.avatar,class_="file",placehouder="Załaduj obraz") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{%- block scripts -%}
    {{ super() }}
    <script src="{{ url_for('static',filename='js/fileinput.min.js') }}"></script>
{%- endblock -%}

app/main/user/templates/user.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <table class="table table-striped table-hover">
        <h1 class="page-header">{{ title }}</h1>
        <thead>
        <tr>
            <th>Nazwa użytkownika</th>
            <th>Email</th>
            <th>Data utworzenia</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr class="animated fadeIn delay-{{ loop.index0 }}">
                <td><a href="{{ url_for('user.detail',user_id=user.id) }}">{{ user.name }}</a></td>
                <td>{{ user.email }}</td>
                <td>{{ user.logs.count() }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

app/main/user/templates/user_cart.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{%- import "bootstrap/wtf.html" as wtf -%}
{% block mycontent %}
    <!-- Tab panes -->
    <h1>Koszyk</h1>
    <div class="tab-content">
    {%- if cart -%}
        {% if request.args.get('show',0)!='1' %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>ID</th>
                    <th>Tytuł</th>
                    <th>Typ</th>
                    <th>Cena</th>
                    <th>Operacje</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_elem in cart %}
                        <td class="hidden-xs">{{ cart_elem.id }}</td>
                        <td class="hidden-xs">{{ cart_elem.name }}</td>
                        <td class="hidden-xs">{{ cart_elem.platform }}</td>
                        <td class="hidden-xs">{{ cart_elem.price }}</td>
                        <td class="hidden-xs"><a class="btn btn-danger"
                                   href="{{ url_for('user.delete_from_cart',user_id=cart_elem.user_id, item_id=cart_elem.item_id) }}">Usuń</a></td>
                        {%- if current_user.is_authenticated -%}

                        {%- endif -%}
                        </td>
                    </tr>


                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>Użytkownik</th>
                    <th>Email</th>
                    <th>Wypozyczenia</th>
                    <th>Data wypożyczenia</th>
                    <th>Data zwrotu</th>
                </tr>
                </thead>
                <tbody>

                    {% for cart_elem in cart %}
                        <tr class="animated fadeIn delay-{{ loop.index0 }}">
                            <td>
                                <p class="visible-xs-block">ID: <span
                                    class="line-wrap">{{ cart_elem.id }}</span>
                                </p>
                                <p class="visible-xs-block">Tytuł: <span
                                    class="line-wrap">{{ cart_elem.name }}</span>
                                </p>
                                <p class="visible-xs-block">Cena: <span
                                        class="line-wrap">{{ cart_elem.price }}</span>
                                </p>
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
            </div>
        {% endif %}
    {%- else -%}
        <div class="container-fluid">Brak danych do wyświetlenia.</div>
    {%- endif -%}      
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
    
        <div class="container">
            <div class="row">
              <div class="col-sm-7">
              </div>
              <div class="col-sm-1">
                <h3>Suma: </h3>
              </div>
              <div class="col-sm-2">
                <h3>{{ total }} PLN</h3>
              </div>
              <div class="col-sm-2">
                <a class="btn btn-success"
                data-toggle="modal"
                data-target="#myModal" style="margin-top: 15px;">Wypożycz</a>
              </div>
            </div>
          </div>
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Finalizacja transakcji</h4>
                    </div>
                    <form method="post" class="form"
                          role="form">
                        {{ form.hidden_tag() }}
                        <div class="modal-body">
                            {{ wtf.form_field(form.street) }}
                            {{ wtf.form_field(form.house_nbr) }}
                            {{ wtf.form_field(form.flat_nbr) }}
                            {{ wtf.form_field(form.postal_code) }}
                            {{ wtf.form_field(form.city) }}
                            {{ wtf.form_field(form.cardholder) }}
                            {{ wtf.form_field(form.card_nbr) }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" name="btn" value="1" class="btn btn-default" data-dismiss="modal">Anuluj
                            </button>
                            {{ wtf.form_field(form.submit,button_map={'submit':'success'}) }}
                    </form>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->  
{% endblock %}

app/main/user/templates/user_detail.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <div class="jumbotron">
        <div class="row">
            {%- if user.avatar_url() -%}
                <div class="col-md-3 animated bounceIn">
                    {%- if current_user.id == user.id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION) -%}
                        <a href="{{ url_for('user.avatar',user_id=user.id) }}" data-toggle="tooltip"
                           data-placement="bottom" title="Edytuj awatar">
                            <div class="avatar avatar-large"
                                 style="background-image: url({{ user.avatar_url() }})"></div>
                        </a>
                    {%- else -%}
                        <div class="avatar avatar-large"
                             style="background-image: url({{ user.avatar_url() }})"></div>
                    {%- endif -%}
                </div>
            {%- endif -%}
            <div class="col-md-6 col-md-offset-1 animated fadeIn">
                <h1 class="page-header">{{ user.name }}
                    {% if user.headline %}
                        <small>{{ user.headline }}</small>
                    {% endif %}

                </h1>

                <p>Email: {{ user.email }}</p>
                <p>Data dołączenia: {{ user.member_since }}</p>
                {% if current_user.id==user.id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION) %}
                    <a class="btn btn-info" href="{{ url_for('user.edit',user_id=user.id) }}">Edytuj</a>
                {% endif %}
                {% if current_user.id==user.id %}
                    <a class="btn btn-danger" href="{{ url_for('auth.change_password',user_id=user.id) }}">Zmień hasło</a>
                {% endif %}

            </div>
        </div>


        {% if user.about_me_html %}
            <h2>
                <small>Profil</small>
            </h2>
            {{ user.about_me_html|safe }}
        {% elif user.about_me %}
            <p>{{ user.about_me }}</p>
        {% endif %}


    </div>
    {%- if user.id != 1 -%}
    <div class="well well-lg" id="log">
        <ul class="nav nav-tabs" role="tablist">
            {% if request.args.get('show',0)!='1' %}
                <li role="presentation" class="active"><a href="#log" role="tab">Aktualne wypożyczenia</a></li>
                <li role="presentation"><a href="{{ url_for('user.detail',user_id=user.id,show=1,_anchor='log') }}"
                                           role="tab">Historia wypożyczeń</a>
                </li>
            {% else %}
                <li role="presentation"><a href="{{ url_for('user.detail',user_id=user.id,show=0,_anchor='log') }}"
                                           role="tab">Aktualne wypożyczenia</a>
                </li>
                <li role="presentation" class="active"><a href="#log" role="tab">Historia wypożyczeń</a></li>
            {% endif %}
        </ul>
        <!-- Tab panes -->
        <div class="tab-content row">
            {% if request.args.get('show',0)!='1' %}
                {%- if logs!=[] -%}
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Wypożyczenie</th>
                            <th class="hidden-xs">Data wypożyczenia</th>
                            <th class="hidden-xs">Data zwrotu</th>
                            {%- if current_user.is_authenticated and current_user.id==user.id -%}
                                <th>Operacje</th>
                            {%- endif -%}
                        </tr>
                        </thead>
                        <tbody>
                        {% for log in logs %}
                            <tr class="animated fadeIn delay-{{ loop.index0 }}">
                                <td><a href="{{ url_for('item.detail',item_id=log.item.id) }}">{{ log.item.title }}</a>
                                    <p class="visible-xs-block">Data wypożyczenia:<span
                                            class="line-wrap">{{ log.borrow_timestamp }}</span>
                                    </p>
                                    <p class="visible-xs-block">Data zwrotu:<span
                                            class="line-wrap">{{ log.return_timestamp }}</span>
                                    </p>
                                </td>
                                <td class="hidden-xs">{{ log.borrow_timestamp }}</td>
                                <td class="hidden-xs">{{ log.return_timestamp }}</td>
                                {%- if current_user.is_authenticated and current_user.id==user.id -%}
                                    <td><a class="btn btn-primary"
                                        href="{{ url_for('log.item_return',log_id=log.id,next=request.path) }}">
                                        Zwrot</a></td>
                                {%- endif -%}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {%- else -%}
                        <div class="container-fluid">Brak danych do wyświetlenia.</div>
                {%- endif -%}                
            {% else %}
                {%- if logs!=[] -%}
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Historia wypożyczeń</th>
                            <th class="hidden-xs">Data wypożyczenia</th>
                            <th class="hidden-xs">Data zwrotu</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for log in logs %}
                            <tr class="animated fadeIn delay-{{ loop.index0 }}">
                                <td><a href="{{ url_for('item.detail',item_id=log.item.id) }}">{{ log.item.title }}</a>
                                    <p class="visible-xs-block">
                                        Data wypożyczenia:<span
                                            class="line-wrap">{{ log.borrow_timestamp }}</span>
                                    </p>
                                    <p class="visible-xs-block">
                                        Data zwrotu:<span
                                            class="line-wrap">{{ log.return_timestamp }}</span>
                                    </p>
                                </td>
                                <td class="hidden-xs">{{ log.borrow_timestamp }}</td>
                                <td class="hidden-xs">{{ log.return_timestamp }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                {%- else -%}
                        <div class="container-fluid">Brak danych do wyświetlenia.</div>
                {%- endif -%}                
            {% endif %}
        {% if pagination and pagination.pages>1 %}
            <div class="container-fluid text-center">
                {{ render_pagination(pagination) }}
            </div>
        {% endif %}
    </div>
    {%- endif -%}
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $('[data-toggle="tooltip"]').tooltip()
    </script>
{% endblock %}

app/main/user/templates/user_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block mycontent %}
    <div class="jumbotron">
        <div class="row">
            {% if user.avatar_url() %}
                <div class="col-md-4 clearfix">
                    <div class="media-object avatar avatar-large"
                         style="background-image: url({{ user.avatar_url() }})"></div>
                </div>
            {% endif %}
            <div class="col-md-8">
                <h1 class="page-header">{{ user.name }}
                    <br>
                    <small>{{ user.email }}</small>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="well well-lg">
                <h3>{{ title }}</h3>
                {{ wtf.quick_form(form,button_map={'submit':'success'}) }}
            </div>
        </div>
    </div>
{% endblock %}

{%- block scripts -%}
    {{ super() }}
    {#    {{ pagedown.include_pagedown() }}#}
    <script src="{{ url_for('static',filename='js/Markdown.Converter.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/Markdown.Sanitizer.min.js') }}"></script>
{%- endblock -%}