app/main/item/forms.py
# -*- coding:utf-8 -*-
from app.models import Item
from flask_pagedown.fields import PageDownField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms import ValidationError
from wtforms.validators import Length, DataRequired, Regexp


class EditItemForm(FlaskForm):
    itemtype = StringField(u"Rodzaj",
                       validators=[DataRequired(message=u"Proszę wypełnić to pole!"),
                                   Length(1, 128, message=u"Długość od 1 do 128 znaków.")])
    platform = StringField(u"Platforma",
                       validators=[DataRequired(message=u"Proszę wypełnić to pole!"),
                                   Length(1, 128, message=u"Długość od 1 do 128 znaków.")])                               
    title = StringField(u"Tytuł",
                        validators=[DataRequired(message=u"Proszę wypełnić to pole!"), Length(1, 128, message=u"Długość od 1 do 128 znaków.")])
    author = StringField(u"Autor", validators=[Length(0, 128, message=u"Długość od 0 do 128 znaków.")])
    publisher = StringField(u"Wydawca", validators=[Length(0, 64, message=u"Długość od 0 do 64 znaków.")])
    image = StringField(u"Zdjęcie", validators=[Length(0, 128, message=u"Długość od 0 do 128 znaków.")])
    pubdate = StringField(u"Data wydania", validators=[Length(0, 32, message=u"Długość od 0 do 32 znaków.")])
    price = StringField(u"Cena", validators=[Length(0, 64, message=u"Długość od 0 do 64 znaków.")])
    summary = PageDownField(u"Podsumowanie")
    amount = IntegerField(u'Ilość')
    submit = SubmitField(u"Zatwierdź")

"""
class AddItemForm(EditItemForm):
    def validate_title(self, filed):
        if Item.query.filter_by(title=filed.data).count():
            raise ValidationError(u'Ten numer ISBN już istnieje w systemie!.')
"""

class SearchForm(FlaskForm):
    search = StringField(validators=[DataRequired()])
    submit = SubmitField(u"Szukaj")

app/main/item/__init__.py
from flask import Blueprint

item = Blueprint('item', __name__, url_prefix='/items',template_folder='templates')

from . import views

app/main/item/views.py
# -*- coding:utf-8 -*-
from app import db
from app.models import Item, Log, Comment, Permission, Cart
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from . import item
from .forms import SearchForm, EditItemForm
from ..comment.forms import CommentForm
from ..decorators import admin_required, permission_required


@item.route('/')
def index():
    search_word = request.args.get('search', None)
    search_form = SearchForm()
    page = request.args.get('page', 1, type=int)

    the_items = Item.query
    if not current_user.can(Permission.UPDATE_ITEM_INFORMATION):
        the_items = Item.query.filter_by(hidden=0)

    if search_word:
        search_word = search_word.strip()
        the_items = the_items.filter(db.or_(
            Item.title.ilike(u"%%%s%%" % search_word), Item.author.ilike(u"%%%s%%" % search_word), Item.itemtype.ilike(
                u"%%%s%%" % search_word), Item.platform.ilike(u"%%%s%%" % search_word)))
        search_form.search.data = search_word
    else:
        the_items = Item.query.order_by(Item.id.desc())

    pagination = the_items.paginate(page, per_page=8)
    result_items = pagination.items
    return render_template("item.html", items=result_items, pagination=pagination, search_form=search_form,
                           title=u"Lista pozycji")


@item.route('/<item_id>/')
def detail(item_id):
    the_item = Item.query.get_or_404(item_id)

    if the_item.hidden and (not current_user.is_authenticated or not current_user.is_administrator()):
        abort(404)

    show = request.args.get('show', 0, type=int)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()

    if show in (1, 2):
        pagination = the_item.logs.filter_by(returned=show - 1) \
            .order_by(Log.borrow_timestamp.desc()).paginate(page, per_page=5)
    else:
        pagination = the_item.comments.filter_by(deleted=0) \
            .order_by(Comment.edit_timestamp.desc()).paginate(page, per_page=5)

    data = pagination.items
    return render_template("item_detail.html", item=the_item, data=data, pagination=pagination, form=form,
                           title=the_item.title)


@item.route('/<int:item_id>/edit/', methods=['GET', 'POST'])
@permission_required(Permission.UPDATE_ITEM_INFORMATION)
def edit(item_id):
    item = Item.query.get_or_404(item_id)
    form = EditItemForm()
    if form.validate_on_submit():
        item.itemtype = form.itemtype.data
        item.platform = form.platform.data
        item.title = form.title.data
        item.author = form.author.data
        item.publisher = form.publisher.data
        item.image = form.image.data
        item.pubdate = form.pubdate.data
        item.price = form.price.data
        item.summary = form.summary.data
        item.amount = form.amount.data
        db.session.add(item)
        db.session.commit()
        flash(u'Dodano pozycję!', 'success')
        return redirect(url_for('item.detail', item_id=item_id))
    form.itemtype.data = item.itemtype
    form.platform.data = item.platform
    form.title.data = item.title
    form.author.data = item.author
    form.publisher.data = item.publisher
    form.image.data = item.image
    form.pubdate.data = item.pubdate
    form.price.data = item.price
    form.summary.data = item.summary or ""
    form.amount.data = item.amount
    return render_template("item_edit.html", form=form, item=item, title=u"Edytuj pozycję")


@item.route('/add/', methods=['GET', 'POST'])
@permission_required(Permission.ADD_ITEM)
def add():
    form = EditItemForm()
    form.amount.data = 3
    if form.validate_on_submit():
        new_item = Item(
            itemtype=form.itemtype.data,
            platform=form.platform.data,
            title=form.title.data,
            author=form.author.data,
            publisher=form.publisher.data,
            image=form.image.data,
            pubdate=form.pubdate.data,
            price=form.price.data,
            summary=form.summary.data or "",
            amount=form.amount.data)
        db.session.add(new_item)
        db.session.commit()
        flash(u'Pozycja %s dodana do bazy!' % new_item.title, 'success')
        return redirect(url_for('item.detail', item_id=new_item.id))
    return render_template("item_edit.html", form=form, title=u"Dodaj nową pozycję")


@item.route('/<int:item_id>/delete/')
@permission_required(Permission.DELETE_ITEM)
def delete(item_id):
    the_item = Item.query.get_or_404(item_id)
    the_item.hidden = 1
    db.session.add(the_item)
    db.session.commit()
    flash(u'Pomyślnie usunięto ksiązki.', 'info')
    return redirect(request.args.get('next') or url_for('item.detail', item_id=item_id))


@item.route('/<int:item_id>/put_back/')
@admin_required
def put_back(item_id):
    the_item = Item.query.get_or_404(item_id)
    the_item.hidden = 0
    db.session.add(the_item)
    db.session.commit()
    flash(u'Pozycja przywrócona.', 'info')
    return redirect(request.args.get('next') or url_for('item.detail', item_id=item_id))

@item.route('/<int:item_id>/add_to_cart/')
@login_required
def add_to_cart(item_id):  
    #item_id = request.args.get('item_id')  
    cart_item = Cart(
        user_id=current_user.id,
        item_id=item_id
    )
    db.session.add(cart_item)
    db.session.commit()    
    flash(u'Pozycja dodana do koszyka!', 'success')
    return redirect(url_for('item.index', item_id=item_id))
    #return redirect(url_for('log.item_borrow',item_id=item_id))

app/main/item/templates/item.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% import "bootstrap/wtf.html" as wtf %}
{% block mycontent %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <form class="form form-horizontal" method="get">
                <div class="input-group  input-group-lg">
                    {{ search_form.search(class_="form-control") }}
                <span class="input-group-btn">
                    <input class="btn btn-primary" id="submit" name="submit" type="submit" value="Szukaj">
                </span>
                </div>
            </form>
        </div>
    </div>

    <h1>{{ title }}</h1>

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Tytuł</th>
            <th class="hidden-xs">Typ</th>
            <th class="hidden-xs">Nośnik</th>
            <th class="hidden-xs">Dostępność</th>
            <th class="hidden-xs">Wypożyczenia ogółem</th>
            {%- if current_user.is_authenticated -%}
                <th>Operacje</th>
            {%- endif -%}
        </tr>
        </thead>
        <tbody>
        {%- for item in items -%}
            <tr class="{% if item.hidden %}danger{% endif %} animated fadeIn delay-{{ loop.index0 }}">
                <td><a href="{{ url_for('item.detail',item_id=item.id) }}">{{ item.title }}</a>
                    <p class="visible-xs-block">{{ item.author }}</p>
                    <p class="visible-xs-block">Dostępność: {{ item.amount }} / {{ item.can_borrow_number() }}</p>
                    <p class="visible-xs-block">Wypożyczone: {{ item.logs.count() }}</p>
                </td>
                <td class="hidden-xs">{{ item.itemtype }}</td>
                <td class="hidden-xs">{{ item.platform }}</td>
                <td class="hidden-xs">{{ item.amount }} / {{ item.can_borrow_number() }}</td>
                <td class="hidden-xs">{{ item.logs.count() }}</td>
                {%- if current_user.is_authenticated -%}
                    <td>
                        {%- if not current_user.is_administrator() -%}
                            <a class="btn btn-success"
                                        {%- if not item.can_borrow(current_user.id,item.id) %} 
                                            disabled="disabled"
                                        {%- else -%}
                                            href="{{ url_for('item.add_to_cart',item_id=item.id,next=request.full_path) }}"    
                                        {%- endif -%}>Dodaj do koszyka</a>
                        {%- endif -%}
                        {% if item.hidden %}
                            {%- if current_user.is_administrator() -%}
                                <a type="button" class="btn btn-info"
                                   href="{{ url_for('item.put_back',item_id=item.id,next=request.full_path) }}">Przywróć</a>
                            {%- endif -%}
                        {% else %}
                            {%- if current_user.can(Permission.DELETE_ITEM) -%}
                                <a type="button" class="btn btn-danger"
                                   href="{{ url_for('item.delete',item_id=item.id,next=request.full_path) }}">Usuń</a>
                            {%- endif -%}
                        {%- endif -%}
                    </td>
                {%- endif -%}
            </tr>
        {%- endfor -%}
        </tbody>
    </table>
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{%- endblock -%}

app/main/item/templates/item_detail.html
{%- extends "base.html" -%}
{%- from "bootstrap/pagination.html" import render_pagination -%}
{%- import "bootstrap/wtf.html" as wtf -%}
{%- block mycontent -%}
    <div class="well well-lg">

        <h1 class="page-header animated fadeInLeft">{{ item.title }}</h1>
        <div class="primary-info">
            {%- if item.image -%}
                <img class="img-responsive" src="{{ item.image }}" alt="{{ item.title }}">
            {%- endif -%}
            <ul class="list-group">
                {%- if item.itemtype -%}
                    <li class="list-group-item">Typ: {{ item.itemtype }}</li>
                {%- endif -%}
                {%- if item.platform -%}
                    <li class="list-group-item">Nośnik: {{ item.platform }}</li>
                {%- endif -%}
                {%- if item.author -%}
                    <li class="list-group-item">Autor: {{ item.author }}</li>
                {%- endif -%}
                {%- if item.publisher -%}
                    <li class="list-group-item">Wydawca: {{ item.publisher }}</li>
                {%- endif -%}
                {%- if item.pubdate -%}
                    <li class="list-group-item">Data wydania: {{ item.pubdate }}</li>
                {%- endif -%}
                {%- if item.price -%}
                    <li class="list-group-item">Cena: {{ item.price }}</li>
                {%- endif -%}
                <li class="list-group-item">Dostępność: {{ item.amount }} / {{ item.can_borrow_number() }}</li>
            </ul>
        </div>
        <br>
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#summary"
                           aria-expanded="true" aria-controls="collapseOne">
                            Opis
                        </a>
                    </h4>
                </div>
                <div id="summary" class="panel-collapse collapse in" role="tabpanel"
                     aria-labelledby="headingOne">
                    <div class="panel-body">
                        {%- if item.summary_html -%}
                            {{ item.summary_html|safe }}
                        {%- else -%}
                            {{ item.summary }}
                        {%- endif -%}
                    </div>
                </div>
            </div>
        </div>

        <div class="btn-group">
            {%- if current_user.is_authenticated -%}
                {%- if not current_user.is_administrator() -%}
                    <a class="btn btn-success"
                        {%- if not item.can_borrow(current_user.id,item.id) %} 
                            disabled="disabled"
                        {%- else -%}
                            href="{{ url_for('item.add_to_cart',item_id=item.id,next=request.full_path) }}"    
                        {%- endif -%}>Dodaj do koszyka</a>
                    </a>
                {%- endif -%}
            {%- endif -%}
            {%- if current_user.can(Permission.UPDATE_ITEM_INFORMATION) -%}
                <a type="button" class="btn btn-warning" href="{{ url_for('item.edit',item_id=item.id) }}">Edytuj
                </a>
            {%- endif -%}

            {%- if item.hidden -%}
                {%- if current_user.is_administrator() -%}
                    <a type="button" class="btn btn-info"
                       href="{{ url_for('item.put_back',item_id=item.id) }}">Przywróć</a>
                {%- endif -%}
            {%- else -%}
                {%- if current_user.can(Permission.DELETE_ITEM) -%}
                    <a type="button" class="btn btn-danger"
                       href="{{ url_for('item.delete',item_id=item.id) }}">Usuń</a>
                {%- endif -%}
            {%- endif -%}
        </div>
    </div>
    <div class="well well-lg">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="log">
            {%- with tabindex= request.args.get('show') or '0' -%}
                <li role="presentation" {%- if tabindex=='0' -%}class="active"{%- endif -%}><a
                        href="{%- if tabindex=='0' -%}#log{%- else -%}{{ url_for('item.detail',item_id=item.id,show=0,_anchor='log') }}{%- endif -%}"
                        role="tab">Recenzje</a></li>
                <li role="presentation" {%- if tabindex=='1' -%}class="active"{%- endif -%}><a
                        href="{%- if tabindex=='1' -%}#log{%- else -%}{{ url_for('item.detail',item_id=item.id,show=1,_anchor='log') }}{%- endif -%}"
                        role="tab">Aktualne wypożyczenia</a></li>
                <li role="presentation" {%- if tabindex=='2' -%}class="active"{%- endif -%}><a
                        href="{%- if tabindex=='2' -%}#log{%- else -%}{{ url_for('item.detail',item_id=item.id,show=2,_anchor='log') }}{%- endif -%}"
                        role="tab">Historia wypożyczeń</a></li>
            {%- endwith -%}
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">

            {%- if (request.args.get('show') or '0')=='0' -%}

                <ul class="list-group">
                    {%- if current_user.is_authenticated -%}
                        <li class="list-group-item list-group-item">
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    <button type="button" class="btn btn-primary btn-block" data-toggle="modal"
                                            data-target="#myModal">
                                        Oceń pozycję
                                    </button>
                                </div>
                            </div>
                        </li>
                    {%- endif -%}
                    {%- for comment in data -%}
                        <li class="list-group-item clearfix">
                            <div class="media">
                                {%- if comment.user.avatar_url() -%}
                                    <div class="media-left">
                                        <a href="{{ url_for('user.detail',user_id=comment.user.id) }}">
                                            <div class="media-object avatar avatar-small"
                                                 style="background-image: url({{ comment.user.avatar_url() }})"></div>
                                        </a>
                                    </div>
                                {%- endif -%}
                                <div class="media-body">
                                    <p class="media-heading"><a
                                            href="{{ url_for('user.detail',user_id=comment.user.id) }}">
                                        {{ comment.user.name }}</a>
                                        <small>{{ comment.user.headline or "" }}</small>
                                    </p>
                                    <p class="list-group-item-text">{{ comment.comment }}</p>
                                    {%- if comment.create_timestamp==comment.edit_timestamp -%}
                                        <h4>
                                            <small>
                                                Przesłany: {{ comment.create_timestamp }}</small>
                                        </h4>
                                    {%- else -%}
                                        <h4>
                                            <small>
                                                Edytowano: {{ comment.edit_timestamp }}</small>
                                        </h4>
                                    {%- endif -%}

                                    {%- if comment.user_id == current_user.id or current_user.can(Permission.DELETE_OTHERS_COMMENT) -%}
                                        <a class="pull-right btn btn-danger btn-sm"
                                           href="{{ url_for('comment.delete',comment_id=comment.id,next=request.url) }}">Usuń</a>
                                    {%- endif -%}
                                </div>
                            </div>
                        </li>
                    {%- endfor -%}
                </ul>
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">{{ current_user.name~'-Recenzja '~item.title }}</h4>
                            </div>
                            <form action="{{ url_for('comment.add',item_id=item.id) }}" method="post" class="form"
                                  role="form">
                                {{ form.hidden_tag() }}
                                <div class="modal-body">
                                    {{ wtf.form_field(form.comment) }}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Anuluj
                                    </button>
                                    {{ wtf.form_field(form.submit,button_map={'submit':'success'}) }}
                            </form>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

            {%- elif request.args.get('show')=='1' -%}
                {%- if data -%}
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Użytkownik</th>
                            <th class="hidden-xs">E-mail</th>
                            <th>Data wypożyczenia</th>
                            <th>Przewidywana data zwrotu</th>
                        </tr>
                        </thead>
                        <tbody>
                        {%- for log in data -%}
                            <tr>
                                <td>
                                    <a href="{{ url_for('user.detail' ,user_id=log.user.id) }}">{{ log.user.name }}</a>
                                </td>
                                <td class="hidden-xs">{{ log.user.email }}</td>
                                </td>
                                <td>{{ log.borrow_timestamp }}</td>
                                <td>{{ log.return_timestamp }}</td>
                            </tr>
                        {%- endfor -%}
                        </tbody>
                    </table>
                {%- else -%}
                    <div class="container-fluid">Brak danych do wyświetlenia.</div>
                {%- endif -%}
            {%- else -%}
                {%- if data -%}
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Użytkownik</th>
                            <th class="hidden-xs">E-mail</th>
                            <th>Data wypożyczenia</th>
                            <th>Data zwrotu</th>
                        </tr>
                        </thead>
                        <tbody>
                        {%- for log in data -%}
                            <tr>
                                <td>
                                    <a href="{{ url_for('user.detail' ,user_id=log.user.id) }}">{{ log.user.name }}</a>
                                </td>
                                <td class="hidden-xs">{{ log.user.email }}</td>
                                </td>
                                <td>{{ log.borrow_timestamp }}</td>
                                <td>{{ log.return_timestamp }}</td>
                            </tr>
                        {%- endfor -%}
                        </tbody>
                    </table>
                {%- else -%}
                    <div class="container-fluid">Brak danych do wyświetlenia.</div>
                {%- endif -%}

            {%- endif -%}
        </div>

        {%- if pagination and pagination.pages > 1 -%}
            <div class="container-fluid text-center">
                {{ render_pagination(pagination,args={'_anchor':'log'}) }}
            </div>
        {%- endif -%}
{%- endblock -%}

app/main/item/templates/item_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/bootstrap-tokenfield.css') }}" rel="stylesheet"/>
{% endblock %}
{%- block mycontent -%}

    <div class="container-fluid well well-lg">

        <h3>{{ title }}</h3>
        {{ wtf.quick_form(form,button_map={'submit':'success'}) }}
    </div>

{%- endblock -%}
{%- block scripts -%}
    {{ super() }}
    {#    {{ pagedown.include_pagedown() }}#}
    <script src="{{ url_for('static',filename='js/Markdown.Converter.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/Markdown.Sanitizer.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap-tokenfield.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/get_item_from_douban.js') }}"></script>
    <script>
        $('#tags').tokenfield({
            delimiter: [",", " ", "/"]
        })

    </script>
{%- endblock -%}